accessControl:
    salt: fEYBv2yA5Pjt7cWrwdbXI1o6kIA2XYZI
api:
    key: D1FB275D5638446D9D466D422F4060CC
feature:
    keyboardControl: false
    printCancelConfirmation: false
    sdSupport: false
plugins:
    announcements:
        _config_version: 1
        channels:
            _blog:
                read_until: 1589460900
            _important:
                read_until: 1521111600
            _octopi:
                read_until: 1573722900
            _plugins:
                read_until: 1590296400
            _releases:
                read_until: 1583322300
        enabled_channels:
        - _important
    discovery:
        upnpUuid: 3783e4a8-7534-4e11-8317-f30ecc0080f9
    errortracking:
        unique_id: 09625205-7af1-49f4-9857-5c2f6ac3ff7e
    softwareupdate:
        _config_version: 7
        checks:
            octoprint:
                branch: null
                checkout_folder: null
                prerelease: false
                prerelease_channel: null
        notify_users: false
    tracking:
        enabled: false
        unique_id: 377595b0-0ec9-462d-965b-643e81200578
printerProfiles:
    default: _default
serial:
    baudrate: 115200
    firmwareDetection: false
    port: /dev/ttyUSB0
server:
    firstRun: false
    onlineCheck:
        enabled: false
    pluginBlacklist:
        enabled: false
    secretKey: 5bZseEJIG43563A8rjpBmETZQgzWdLA3
    seenWizards:
        corewizard: 3
        tracking: null
temperature:
    profiles:
    -   bed: 100
        chamber: null
        extruder: 210
        name: ABS
    -   bed: 60
        chamber: null
        extruder: 180
        name: PLA
